import { Palette, StyleMetrics } from "style.slint";
import { Button } from "std-widgets.slint";

export component Page inherits Rectangle {
    background: #ffffff;
}

export component TitleBar inherits Rectangle {
    in property <string> text <=> text-item.text;
    width: 100%; // parent.width does not work, because components can't access outside elements
    height: 32px;
    background: Palette.background;
    padding-top: StyleMetrics.padding;
    padding-bottom: StyleMetrics.padding;

    // To display the text
    text-item := Text {
        text: "TitleBar";
        font-size: 16px;
    }
}

export component StatusBar inherits Rectangle {
    in property <string> text <=> text-item.text;

    background: Palette.background;
    height: StyleMetrics.status-height; // 12px // (custom-height)

    text-item := Text {
        width: parent.width;
        horizontal-alignment: center;
        vertical-alignment: center;
    }
}

export component Selector {
    in-out property <int> value: 1;

    callback decrease(int) -> int;
    callback increase(int) -> int;

    VerticalLayout {
        Button {
            text: "+";
            height: StyleMetrics.line-height;
            clicked => {
                root.value = root.increase(root.value);
            }
        }

        value-text := Text {
            text: "\{root.value}";
            font-size: StyleMetrics.line-height;
            horizontal-alignment: center;
        }

        Button {
            text: "-";
            height: StyleMetrics.line-height;
            clicked => {
                root.value = root.decrease(root.value);
            }
        }
    }
}

export component AppWindow inherits Window {
    width: 320px;
    height: 240px;
    in property status-base-text <=> status-bar.text;

    VerticalLayout {
        TitleBar {
            text: "Dice Roller";
        }

        @children // The actual window context will be placed here


        status-bar := StatusBar { }
    }
}
